### ISSUE TITLE
compiling on 1.8

### ISSUE THREAD

**Issue by sejcjan** [goodwinuser/CalDav4J#1]
Hello, seems it is not possible to compile on JDK 1.8. because of reference tp "var" as restrictred type name.
DId you please compile it on 1.8 or what JDK to use? I tried JDK11 but here is error in .toList() non existing method.

**Comment by goodwinuser** [comment]
Hello, I have updated the jdk version. 
I also created new correct versions of the library for 8, 11, 17 java versions.
